// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.templateitem.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class TemplateItemQueryRequest implements Request {
  @Schema(
      title = "名称"
  )
  private String name;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
