// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.payitemconfig.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;

@Schema
public class PayItemConfigCreateRequest implements Request {
  @Schema(
      title = "交易类型编码"
  )
  private String tradeTypeCode;

  @Schema(
      title = "支付类型"
  )
  private Integer payType;

  @Schema(
      title = "是否支持开票"
  )
  private Integer validStatus;

  public String getTradeTypeCode() {
    return tradeTypeCode;
  }

  public void setTradeTypeCode(String tradeTypeCode) {
    this.tradeTypeCode = tradeTypeCode;
  }

  public Integer getPayType() {
    return payType;
  }

  public void setPayType(Integer payType) {
    this.payType = payType;
  }

  public Integer getValidStatus() {
    return validStatus;
  }

  public void setValidStatus(Integer validStatus) {
    this.validStatus = validStatus;
  }
}
