// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.assetlifecycle.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.asset.assetlifecycle.AssetLifecycle;
import java.lang.Long;

public interface AssetLifecycleRepository extends BaseRepository<AssetLifecycle, Long> {

}
