// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.reviserecord.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.trade.reviserecord.ReviseRecord;
import com.only4play.system.domain.trade.reviserecord.creator.ReviseRecordCreator;
import com.only4play.system.domain.trade.reviserecord.query.ReviseRecordQuery;
import com.only4play.system.domain.trade.reviserecord.request.ReviseRecordCreateRequest;
import com.only4play.system.domain.trade.reviserecord.request.ReviseRecordQueryRequest;
import com.only4play.system.domain.trade.reviserecord.request.ReviseRecordUpdateRequest;
import com.only4play.system.domain.trade.reviserecord.response.ReviseRecordResponse;
import com.only4play.system.domain.trade.reviserecord.updater.ReviseRecordUpdater;
import com.only4play.system.domain.trade.reviserecord.vo.ReviseRecordVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface ReviseRecordMapper {
  ReviseRecordMapper INSTANCE = Mappers.getMapper(ReviseRecordMapper.class);

  ReviseRecord dtoToEntity(ReviseRecordCreator dto);

  ReviseRecordUpdater request2Updater(ReviseRecordUpdateRequest request);

  ReviseRecordCreator request2Dto(ReviseRecordCreateRequest request);

  ReviseRecordQuery request2Query(ReviseRecordQueryRequest request);

  ReviseRecordResponse vo2Response(ReviseRecordVO vo);

  default ReviseRecordResponse vo2CustomResponse(ReviseRecordVO vo) {
    ReviseRecordResponse response = vo2Response(vo);
    return response;
  }
}
