// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.templateitem.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.template.templateitem.creator.TemplateItemCreator;
import com.only4play.system.domain.template.templateitem.query.TemplateItemQuery;
import com.only4play.system.domain.template.templateitem.updater.TemplateItemUpdater;
import com.only4play.system.domain.template.templateitem.vo.TemplateItemVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ITemplateItemService {
  /**
   * create
   */
  Long createTemplateItem(TemplateItemCreator creator);

  /**
   * update
   */
  void updateTemplateItem(TemplateItemUpdater updater);

  /**
   * valid
   */
  void validTemplateItem(Long id);

  /**
   * invalid
   */
  void invalidTemplateItem(Long id);

  /**
   * findById
   */
  TemplateItemVO findById(Long id);

  /**
   * findByPage
   */
  Page<TemplateItemVO> findByPage(PageRequestWrapper<TemplateItemQuery> query);
}
