// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.message.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.message.SmsSendRecord;
import java.lang.Long;

public interface SmsSendRecordRepository extends BaseRepository<SmsSendRecord, Long> {
}
