// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.objecttemplate.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.template.objecttemplate.TemplateCategory;
import com.only4play.system.domain.template.objecttemplate.creator.TemplateCategoryCreator;
import com.only4play.system.domain.template.objecttemplate.query.TemplateCategoryQuery;
import com.only4play.system.domain.template.objecttemplate.request.TemplateCategoryCreateRequest;
import com.only4play.system.domain.template.objecttemplate.request.TemplateCategoryQueryRequest;
import com.only4play.system.domain.template.objecttemplate.request.TemplateCategoryUpdateRequest;
import com.only4play.system.domain.template.objecttemplate.response.TemplateCategoryResponse;
import com.only4play.system.domain.template.objecttemplate.updater.TemplateCategoryUpdater;
import com.only4play.system.domain.template.objecttemplate.vo.TemplateCategoryVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface TemplateCategoryMapper {
  TemplateCategoryMapper INSTANCE = Mappers.getMapper(TemplateCategoryMapper.class);

  TemplateCategory dtoToEntity(TemplateCategoryCreator dto);

  TemplateCategoryUpdater request2Updater(TemplateCategoryUpdateRequest request);

  TemplateCategoryCreator request2Dto(TemplateCategoryCreateRequest request);

  TemplateCategoryQuery request2Query(TemplateCategoryQueryRequest request);

  TemplateCategoryResponse vo2Response(TemplateCategoryVO vo);

  default TemplateCategoryResponse vo2CustomResponse(TemplateCategoryVO vo) {
    TemplateCategoryResponse response = vo2Response(vo);
    return response;
  }
}
