// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.asset.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.asset.asset.Asset;
import java.lang.Long;

public interface AssetRepository extends BaseRepository<Asset, Long> {
}
