// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.objecttemplate.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.template.objecttemplate.TemplateCategory;
import java.lang.Long;

public interface TemplateCategoryRepository extends BaseRepository<TemplateCategory, Long> {
}
