// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.objecttemplate.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.template.objecttemplate.TemplateItemRel;
import java.lang.Long;

public interface TemplateItemRelRepository extends BaseRepository<TemplateItemRel, Long> {
}
