// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.orderlifecycle.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.trade.orderlifecycle.creator.OrderLifecycleCreator;
import com.only4play.system.domain.trade.orderlifecycle.query.OrderLifecycleQuery;
import com.only4play.system.domain.trade.orderlifecycle.updater.OrderLifecycleUpdater;
import com.only4play.system.domain.trade.orderlifecycle.vo.OrderLifecycleVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IOrderLifecycleService {
  /**
   * create
   */
  Long createOrderLifecycle(OrderLifecycleCreator creator);

  /**
   * update
   */
  void updateOrderLifecycle(OrderLifecycleUpdater updater);

  /**
   * valid
   */
  void validOrderLifecycle(Long id);

  /**
   * invalid
   */
  void invalidOrderLifecycle(Long id);

  /**
   * findById
   */
  OrderLifecycleVO findById(Long id);

  /**
   * findByPage
   */
  Page<OrderLifecycleVO> findByPage(PageRequestWrapper<OrderLifecycleQuery> query);
}
