// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.enterpriseentity.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.enterpriseentity.EnterpriseEntity;
import java.lang.Long;
import java.util.Optional;

public interface EnterpriseEntityRepository extends BaseRepository<EnterpriseEntity, Long> {

  Optional<EnterpriseEntity> findByTaxCode(String taxCode);
}
