// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.resource.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.permission.resource.creator.ResourceCreator;
import com.only4play.system.domain.permission.resource.query.ResourceQuery;
import com.only4play.system.domain.permission.resource.updater.ResourceUpdater;
import com.only4play.system.domain.permission.resource.vo.ResourceVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IResourceService {
  /**
   * create
   */
  Long createResource(ResourceCreator creator);

  /**
   * update
   */
  void updateResource(ResourceUpdater updater);

  /**
   * valid
   */
  void validResource(Long id);

  /**
   * invalid
   */
  void invalidResource(Long id);

  /**
   * findById
   */
  ResourceVO findById(Long id);

  /**
   * findByPage
   */
  Page<ResourceVO> findByPage(PageRequestWrapper<ResourceQuery> query);
}
