// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.warehouse.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.asset.warehouse.Warehouse;
import com.only4play.system.domain.asset.warehouse.creator.WarehouseCreator;
import com.only4play.system.domain.asset.warehouse.query.WarehouseQuery;
import com.only4play.system.domain.asset.warehouse.request.WarehouseCreateRequest;
import com.only4play.system.domain.asset.warehouse.request.WarehouseQueryRequest;
import com.only4play.system.domain.asset.warehouse.request.WarehouseUpdateRequest;
import com.only4play.system.domain.asset.warehouse.response.WarehouseResponse;
import com.only4play.system.domain.asset.warehouse.updater.WarehouseUpdater;
import com.only4play.system.domain.asset.warehouse.vo.WarehouseVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface WarehouseMapper {
  WarehouseMapper INSTANCE = Mappers.getMapper(WarehouseMapper.class);

  Warehouse dtoToEntity(WarehouseCreator dto);

  WarehouseUpdater request2Updater(WarehouseUpdateRequest request);

  WarehouseCreator request2Dto(WarehouseCreateRequest request);

  WarehouseQuery request2Query(WarehouseQueryRequest request);

  WarehouseResponse vo2Response(WarehouseVO vo);

  default WarehouseResponse vo2CustomResponse(WarehouseVO vo) {
    WarehouseResponse response = vo2Response(vo);
    return response;
  }
}
