// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.platform.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.permission.platform.creator.PlatformCreator;
import com.only4play.system.domain.permission.platform.query.PlatformQuery;
import com.only4play.system.domain.permission.platform.updater.PlatformUpdater;
import com.only4play.system.domain.permission.platform.vo.PlatformVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IPlatformService {
  /**
   * create
   */
  Long createPlatform(PlatformCreator creator);

  /**
   * update
   */
  void updatePlatform(PlatformUpdater updater);

  /**
   * valid
   */
  void validPlatform(Long id);

  /**
   * invalid
   */
  void invalidPlatform(Long id);

  /**
   * findById
   */
  PlatformVO findById(Long id);

  /**
   * findByPage
   */
  Page<PlatformVO> findByPage(PageRequestWrapper<PlatformQuery> query);
}
