// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.role.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class RoleCreateRequest implements Request {
  @Schema(
      title = "角色编码"
  )
  private String role;

  @Schema(
      title = "角色名称"
  )
  private String name;

  @Schema(
      title = "平台Id"
  )
  private Long platformId;

  @Schema(
      title = "备注"
  )
  private String remark;

  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getPlatformId() {
    return platformId;
  }

  public void setPlatformId(Long platformId) {
    this.platformId = platformId;
  }

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }
}
