// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.order.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.trade.order.OrderBase;
import java.lang.Long;

public interface OrderBaseRepository extends BaseRepository<OrderBase, Long> {
}
