// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.assetlifecycle.response;

import com.only4play.common.constants.ValidStatus;
import com.only4play.common.model.AbstractJpaResponse;
import com.only4play.system.domain.asset.assetrecord.InOutBizType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class AssetLifecycleResponse extends AbstractJpaResponse {
  @Schema(
      title = "资产名称"
  )
  private String name;

  @Schema(
      title = "资产Id"
  )
  private Long assetsId;

  @Schema(
      title = "唯一编码"
  )
  private String uniqueCode;

  @Schema(
      title = "备注"
  )
  private String remark;

  @Schema(
      title = "仓库名称"
  )
  private String houseName;

  @Schema(
      title = "仓库id"
  )
  private Long houseId;

  @Schema(
      title = "出入库业务类型"
  )
  private InOutBizType inOutBizType;

  @Schema(
      title = "操作人"
  )
  private String operateUser;

  @Schema(
      title = "validStatus"
  )
  private ValidStatus validStatus;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getAssetsId() {
    return assetsId;
  }

  public void setAssetsId(Long assetsId) {
    this.assetsId = assetsId;
  }

  public String getUniqueCode() {
    return uniqueCode;
  }

  public void setUniqueCode(String uniqueCode) {
    this.uniqueCode = uniqueCode;
  }

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public String getHouseName() {
    return houseName;
  }

  public void setHouseName(String houseName) {
    this.houseName = houseName;
  }

  public Long getHouseId() {
    return houseId;
  }

  public void setHouseId(Long houseId) {
    this.houseId = houseId;
  }

  public InOutBizType getInOutBizType() {
    return inOutBizType;
  }

  public void setInOutBizType(InOutBizType inOutBizType) {
    this.inOutBizType = inOutBizType;
  }

  public String getOperateUser() {
    return operateUser;
  }

  public void setOperateUser(String operateUser) {
    this.operateUser = operateUser;
  }

  public ValidStatus getValidStatus() {
    return validStatus;
  }

  public void setValidStatus(ValidStatus validStatus) {
    this.validStatus = validStatus;
  }
}
