// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.payitemconfig.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.invoice.payitemconfig.creator.PayItemConfigCreator;
import com.only4play.system.domain.invoice.payitemconfig.query.PayItemConfigQuery;
import com.only4play.system.domain.invoice.payitemconfig.updater.PayItemConfigUpdater;
import com.only4play.system.domain.invoice.payitemconfig.vo.PayItemConfigVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IPayItemConfigService {
  /**
   * create
   */
  Long createPayItemConfig(PayItemConfigCreator creator);

  /**
   * update
   */
  void updatePayItemConfig(PayItemConfigUpdater updater);

  /**
   * valid
   */
  void validPayItemConfig(Long id);

  /**
   * invalid
   */
  void invalidPayItemConfig(Long id);

  /**
   * findById
   */
  PayItemConfigVO findById(Long id);

  /**
   * findByPage
   */
  Page<PayItemConfigVO> findByPage(PageRequestWrapper<PayItemConfigQuery> query);
}
