// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.payitemconfig.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.invoice.payitemconfig.PayItemConfig;
import com.only4play.system.domain.invoice.payitemconfig.creator.PayItemConfigCreator;
import com.only4play.system.domain.invoice.payitemconfig.mapper.PayItemConfigMapper;
import com.only4play.system.domain.invoice.payitemconfig.query.PayItemConfigQuery;
import com.only4play.system.domain.invoice.payitemconfig.repository.PayItemConfigRepository;
import com.only4play.system.domain.invoice.payitemconfig.updater.PayItemConfigUpdater;
import com.only4play.system.domain.invoice.payitemconfig.vo.PayItemConfigVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class PayItemConfigServiceImpl implements IPayItemConfigService {
  private final PayItemConfigRepository payItemConfigRepository;

  /**
   * createImpl
   */
  @Override
  public Long createPayItemConfig(PayItemConfigCreator creator) {
    Optional<PayItemConfig> payItemConfig = EntityOperations.doCreate(payItemConfigRepository)
    .create(() -> PayItemConfigMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> {})
    .execute();
    return payItemConfig.isPresent() ? payItemConfig.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updatePayItemConfig(PayItemConfigUpdater updater) {
    EntityOperations.doUpdate(payItemConfigRepository)
    .loadById(updater.getId())
    .update(e -> updater.updatePayItemConfig(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validPayItemConfig(Long id) {
    EntityOperations.doUpdate(payItemConfigRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidPayItemConfig(Long id) {
    EntityOperations.doUpdate(payItemConfigRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public PayItemConfigVO findById(Long id) {
    Optional<PayItemConfig> payItemConfig =  payItemConfigRepository.findById(id);
    return new PayItemConfigVO(payItemConfig.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<PayItemConfigVO> findByPage(PageRequestWrapper<PayItemConfigQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<PayItemConfig> page = payItemConfigRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new PayItemConfigVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
