// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.user.creator.UserBaseCreator;
import com.only4play.system.domain.user.query.UserBaseQuery;
import com.only4play.system.domain.user.updater.UserBaseUpdater;
import com.only4play.system.domain.user.vo.UserBaseVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IUserBaseService {
  /**
   * create
   */
  Long createUserBase(UserBaseCreator creator);

  /**
   * update
   */
  void updateUserBase(UserBaseUpdater updater);

  /**
   * valid
   */
  void validUserBase(Long id);

  /**
   * invalid
   */
  void invalidUserBase(Long id);

  /**
   * findById
   */
  UserBaseVO findById(Long id);

  /**
   * findByPage
   */
  Page<UserBaseVO> findByPage(PageRequestWrapper<UserBaseQuery> query);
}
