// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.user.creator.UserAccountCreator;
import com.only4play.system.domain.user.query.UserAccountQuery;
import com.only4play.system.domain.user.updater.UserAccountUpdater;
import com.only4play.system.domain.user.vo.UserAccountVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IUserAccountService {
  /**
   * create
   */
  Long createUserAccount(UserAccountCreator creator);

  /**
   * update
   */
  void updateUserAccount(UserAccountUpdater updater);

  /**
   * valid
   */
  void validUserAccount(Long id);

  /**
   * invalid
   */
  void invalidUserAccount(Long id);

  /**
   * findById
   */
  UserAccountVO findById(Long id);

  /**
   * findByPage
   */
  Page<UserAccountVO> findByPage(PageRequestWrapper<UserAccountQuery> query);
}
