// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.reviserecord.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class ReviseRecordQueryRequest implements Request {
  @Schema(
      title = "唯一流水"
  )
  private Long flowNo;

  @Schema(
      title = "表名"
  )
  private String tableName;

  public Long getFlowNo() {
    return flowNo;
  }

  public void setFlowNo(Long flowNo) {
    this.flowNo = flowNo;
  }

  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }
}
