// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.invoice.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.invoice.Invoice;
import java.lang.Long;

public interface InvoiceRepository extends BaseRepository<Invoice, Long> {
}
