// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.invoice.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.invoice.InvoiceItem;
import java.lang.Long;

public interface InvoiceItemRepository extends BaseRepository<InvoiceItem, Long> {
}
