// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.system.domain.admin.creator.AdminUserCreator;
import com.only4play.system.domain.admin.mapper.AdminUserMapper;
import com.only4play.system.domain.admin.query.AdminUserQuery;
import com.only4play.system.domain.admin.request.AdminUserCreateRequest;
import com.only4play.system.domain.admin.request.AdminUserQueryRequest;
import com.only4play.system.domain.admin.request.AdminUserUpdateRequest;
import com.only4play.system.domain.admin.response.AdminUserResponse;
import com.only4play.system.domain.admin.service.IAdminUserService;
import com.only4play.system.domain.admin.updater.AdminUserUpdater;
import com.only4play.system.domain.admin.vo.AdminUserVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("adminUser/v1")
@RequiredArgsConstructor
public class AdminUserController {
  private final IAdminUserService adminUserService;

  /**
   * createRequest
   */
  @PostMapping("createAdminUser")
  public JsonObject<Long> createAdminUser(@RequestBody AdminUserCreateRequest request) {
    AdminUserCreator creator = AdminUserMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(adminUserService.createAdminUser(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateAdminUser")
  public JsonObject<String> updateAdminUser(@RequestBody AdminUserUpdateRequest request) {
    AdminUserUpdater updater = AdminUserMapper.INSTANCE.request2Updater(request);
    adminUserService.updateAdminUser(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validAdminUser(@PathVariable Long id) {
    adminUserService.validAdminUser(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidAdminUser(@PathVariable Long id) {
    adminUserService.invalidAdminUser(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<AdminUserResponse> findById(@PathVariable Long id) {
    AdminUserVO vo = adminUserService.findById(id);
    AdminUserResponse response = AdminUserMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<AdminUserResponse>> findByPage(
      @RequestBody PageRequestWrapper<AdminUserQueryRequest> request) {
    PageRequestWrapper<AdminUserQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(AdminUserMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<AdminUserVO> page = adminUserService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> AdminUserMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }
}
