// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.EnumVo;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.common.utils.EnumDictUtils;
import com.only4play.system.domain.template.objecttemplate.creator.ObjectTemplateCreator;
import com.only4play.system.domain.template.objecttemplate.mapper.ObjectTemplateMapper;
import com.only4play.system.domain.template.objecttemplate.query.ObjectTemplateQuery;
import com.only4play.system.domain.template.objecttemplate.request.ObjectTemplateCreateRequest;
import com.only4play.system.domain.template.objecttemplate.request.ObjectTemplateQueryRequest;
import com.only4play.system.domain.template.objecttemplate.request.ObjectTemplateUpdateRequest;
import com.only4play.system.domain.template.objecttemplate.response.ObjectTemplateResponse;
import com.only4play.system.domain.template.objecttemplate.service.IObjectTemplateService;
import com.only4play.system.domain.template.objecttemplate.updater.ObjectTemplateUpdater;
import com.only4play.system.domain.template.objecttemplate.vo.ObjectTemplateVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("objectTemplate/v1")
@RequiredArgsConstructor
public class ObjectTemplateController {
  private final IObjectTemplateService objectTemplateService;

  /**
   * createRequest
   */
  @PostMapping("createObjectTemplate")
  public JsonObject<Long> createObjectTemplate(@RequestBody ObjectTemplateCreateRequest request) {
    ObjectTemplateCreator creator = ObjectTemplateMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(objectTemplateService.createObjectTemplate(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateObjectTemplate")
  public JsonObject<String> updateObjectTemplate(@RequestBody ObjectTemplateUpdateRequest request) {
    ObjectTemplateUpdater updater = ObjectTemplateMapper.INSTANCE.request2Updater(request);
    objectTemplateService.updateObjectTemplate(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validObjectTemplate(@PathVariable Long id) {
    objectTemplateService.validObjectTemplate(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidObjectTemplate(@PathVariable Long id) {
    objectTemplateService.invalidObjectTemplate(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<ObjectTemplateResponse> findById(@PathVariable Long id) {
    ObjectTemplateVO vo = objectTemplateService.findById(id);
    ObjectTemplateResponse response = ObjectTemplateMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<ObjectTemplateResponse>> findByPage(
      @RequestBody PageRequestWrapper<ObjectTemplateQueryRequest> request) {
    PageRequestWrapper<ObjectTemplateQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(ObjectTemplateMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<ObjectTemplateVO> page = objectTemplateService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> ObjectTemplateMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }

}
