// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.system.domain.trade.orderlifecycle.creator.OrderLifecycleCreator;
import com.only4play.system.domain.trade.orderlifecycle.mapper.OrderLifecycleMapper;
import com.only4play.system.domain.trade.orderlifecycle.query.OrderLifecycleQuery;
import com.only4play.system.domain.trade.orderlifecycle.request.OrderLifecycleCreateRequest;
import com.only4play.system.domain.trade.orderlifecycle.request.OrderLifecycleQueryRequest;
import com.only4play.system.domain.trade.orderlifecycle.request.OrderLifecycleUpdateRequest;
import com.only4play.system.domain.trade.orderlifecycle.response.OrderLifecycleResponse;
import com.only4play.system.domain.trade.orderlifecycle.service.IOrderLifecycleService;
import com.only4play.system.domain.trade.orderlifecycle.updater.OrderLifecycleUpdater;
import com.only4play.system.domain.trade.orderlifecycle.vo.OrderLifecycleVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("orderLifecycle/v1")
@RequiredArgsConstructor
public class OrderLifecycleController {
  private final IOrderLifecycleService orderLifecycleService;

  /**
   * createRequest
   */
  @PostMapping("createOrderLifecycle")
  public JsonObject<Long> createOrderLifecycle(@RequestBody OrderLifecycleCreateRequest request) {
    OrderLifecycleCreator creator = OrderLifecycleMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(orderLifecycleService.createOrderLifecycle(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateOrderLifecycle")
  public JsonObject<String> updateOrderLifecycle(@RequestBody OrderLifecycleUpdateRequest request) {
    OrderLifecycleUpdater updater = OrderLifecycleMapper.INSTANCE.request2Updater(request);
    orderLifecycleService.updateOrderLifecycle(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validOrderLifecycle(@PathVariable Long id) {
    orderLifecycleService.validOrderLifecycle(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidOrderLifecycle(@PathVariable Long id) {
    orderLifecycleService.invalidOrderLifecycle(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<OrderLifecycleResponse> findById(@PathVariable Long id) {
    OrderLifecycleVO vo = orderLifecycleService.findById(id);
    OrderLifecycleResponse response = OrderLifecycleMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<OrderLifecycleResponse>> findByPage(
      @RequestBody PageRequestWrapper<OrderLifecycleQueryRequest> request) {
    PageRequestWrapper<OrderLifecycleQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(OrderLifecycleMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<OrderLifecycleVO> page = orderLifecycleService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> OrderLifecycleMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }
}
