// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.system.domain.trade.order.creator.OrderBaseCreator;
import com.only4play.system.domain.trade.order.mapper.OrderBaseMapper;
import com.only4play.system.domain.trade.order.query.OrderBaseQuery;
import com.only4play.system.domain.trade.order.request.OrderBaseCreateRequest;
import com.only4play.system.domain.trade.order.request.OrderBaseQueryRequest;
import com.only4play.system.domain.trade.order.request.OrderBaseUpdateRequest;
import com.only4play.system.domain.trade.order.response.OrderBaseResponse;
import com.only4play.system.domain.trade.order.service.IOrderBaseService;
import com.only4play.system.domain.trade.order.updater.OrderBaseUpdater;
import com.only4play.system.domain.trade.order.vo.OrderBaseVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("orderBase/v1")
@RequiredArgsConstructor
public class OrderBaseController {
  private final IOrderBaseService orderBaseService;

  /**
   * createRequest
   */
  @PostMapping("createOrderBase")
  public JsonObject<Long> createOrderBase(@RequestBody OrderBaseCreateRequest request) {
    OrderBaseCreator creator = OrderBaseMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(orderBaseService.createOrderBase(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateOrderBase")
  public JsonObject<String> updateOrderBase(@RequestBody OrderBaseUpdateRequest request) {
    OrderBaseUpdater updater = OrderBaseMapper.INSTANCE.request2Updater(request);
    orderBaseService.updateOrderBase(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validOrderBase(@PathVariable Long id) {
    orderBaseService.validOrderBase(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidOrderBase(@PathVariable Long id) {
    orderBaseService.invalidOrderBase(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<OrderBaseResponse> findById(@PathVariable Long id) {
    OrderBaseVO vo = orderBaseService.findById(id);
    OrderBaseResponse response = OrderBaseMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<OrderBaseResponse>> findByPage(
      @RequestBody PageRequestWrapper<OrderBaseQueryRequest> request) {
    PageRequestWrapper<OrderBaseQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(OrderBaseMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<OrderBaseVO> page = orderBaseService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> OrderBaseMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }
}
