// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.EnumVo;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.common.utils.EnumDictUtils;
import com.only4play.system.domain.template.selectdict.DictType;
import com.only4play.system.domain.template.selectdict.creator.SelectDictCreator;
import com.only4play.system.domain.template.selectdict.mapper.SelectDictMapper;
import com.only4play.system.domain.template.selectdict.query.SelectDictQuery;
import com.only4play.system.domain.template.selectdict.request.SelectDictCreateRequest;
import com.only4play.system.domain.template.selectdict.request.SelectDictQueryRequest;
import com.only4play.system.domain.template.selectdict.request.SelectDictUpdateRequest;
import com.only4play.system.domain.template.selectdict.response.SelectDictResponse;
import com.only4play.system.domain.template.selectdict.service.ISelectDictService;
import com.only4play.system.domain.template.selectdict.updater.SelectDictUpdater;
import com.only4play.system.domain.template.selectdict.vo.SelectDictVO;
import java.lang.Long;
import java.lang.String;
import java.util.List;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("selectDict/v1")
@RequiredArgsConstructor
public class SelectDictController {
  private final ISelectDictService selectDictService;

  /**
   * createRequest
   */
  @PostMapping("createSelectDict")
  public JsonObject<Long> createSelectDict(@RequestBody SelectDictCreateRequest request) {
    SelectDictCreator creator = SelectDictMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(selectDictService.createSelectDict(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateSelectDict")
  public JsonObject<String> updateSelectDict(@RequestBody SelectDictUpdateRequest request) {
    SelectDictUpdater updater = SelectDictMapper.INSTANCE.request2Updater(request);
    selectDictService.updateSelectDict(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validSelectDict(@PathVariable Long id) {
    selectDictService.validSelectDict(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidSelectDict(@PathVariable Long id) {
    selectDictService.invalidSelectDict(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<SelectDictResponse> findById(@PathVariable Long id) {
    SelectDictVO vo = selectDictService.findById(id);
    SelectDictResponse response = SelectDictMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<SelectDictResponse>> findByPage(
      @RequestBody PageRequestWrapper<SelectDictQueryRequest> request) {
    PageRequestWrapper<SelectDictQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(SelectDictMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<SelectDictVO> page = selectDictService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> SelectDictMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }

  @GetMapping(value = "dictType")
  public JsonObject<List<EnumVo>> dictType(){
    return JsonObject.success(EnumDictUtils.getEnumDictVo(DictType.class));
  }
}
