// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.system.domain.user.creator.UserBaseCreator;
import com.only4play.system.domain.user.mapper.UserBaseMapper;
import com.only4play.system.domain.user.query.UserBaseQuery;
import com.only4play.system.domain.user.request.UserBaseCreateRequest;
import com.only4play.system.domain.user.request.UserBaseQueryRequest;
import com.only4play.system.domain.user.request.UserBaseUpdateRequest;
import com.only4play.system.domain.user.response.UserBaseResponse;
import com.only4play.system.domain.user.service.IUserBaseService;
import com.only4play.system.domain.user.updater.UserBaseUpdater;
import com.only4play.system.domain.user.vo.UserBaseVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("userBase/v1")
@RequiredArgsConstructor
public class UserBaseController {
  private final IUserBaseService userBaseService;

  /**
   * createRequest
   */
  @PostMapping("createUserBase")
  public JsonObject<Long> createUserBase(@RequestBody UserBaseCreateRequest request) {
    UserBaseCreator creator = UserBaseMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(userBaseService.createUserBase(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateUserBase")
  public JsonObject<String> updateUserBase(@RequestBody UserBaseUpdateRequest request) {
    UserBaseUpdater updater = UserBaseMapper.INSTANCE.request2Updater(request);
    userBaseService.updateUserBase(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validUserBase(@PathVariable Long id) {
    userBaseService.validUserBase(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidUserBase(@PathVariable Long id) {
    userBaseService.invalidUserBase(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<UserBaseResponse> findById(@PathVariable Long id) {
    UserBaseVO vo = userBaseService.findById(id);
    UserBaseResponse response = UserBaseMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<UserBaseResponse>> findByPage(
      @RequestBody PageRequestWrapper<UserBaseQueryRequest> request) {
    PageRequestWrapper<UserBaseQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(UserBaseMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<UserBaseVO> page = userBaseService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> UserBaseMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }
}
