// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.objectsku.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.objectsku.SkuAttribute;
import java.lang.Long;

public interface SkuAttributeRepository extends BaseRepository<SkuAttribute, Long> {
}
