// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.message.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.message.creator.SmsSendRecordCreator;
import com.only4play.system.domain.message.query.SmsSendRecordQuery;
import com.only4play.system.domain.message.updater.SmsSendRecordUpdater;
import com.only4play.system.domain.message.vo.SmsSendRecordVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ISmsSendRecordService {
  /**
   * create
   */
  Long createSmsSendRecord(SmsSendRecordCreator creator);

  /**
   * update
   */
  void updateSmsSendRecord(SmsSendRecordUpdater updater);

  /**
   * valid
   */
  void validSmsSendRecord(Long id);

  /**
   * invalid
   */
  void invalidSmsSendRecord(Long id);

  /**
   * findById
   */
  SmsSendRecordVO findById(Long id);

  /**
   * findByPage
   */
  Page<SmsSendRecordVO> findByPage(PageRequestWrapper<SmsSendRecordQuery> query);
}
