// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.message.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.message.SmsSendRecord;
import com.only4play.system.domain.message.creator.SmsSendRecordCreator;
import com.only4play.system.domain.message.mapper.SmsSendRecordMapper;
import com.only4play.system.domain.message.query.SmsSendRecordQuery;
import com.only4play.system.domain.message.repository.SmsSendRecordRepository;
import com.only4play.system.domain.message.updater.SmsSendRecordUpdater;
import com.only4play.system.domain.message.vo.SmsSendRecordVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class SmsSendRecordServiceImpl implements ISmsSendRecordService {
  private final SmsSendRecordRepository smsSendRecordRepository;

  /**
   * createImpl
   */
  @Override
  public Long createSmsSendRecord(SmsSendRecordCreator creator) {
    Optional<SmsSendRecord> smsSendRecord = EntityOperations.doCreate(smsSendRecordRepository)
    .create(() -> SmsSendRecordMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return smsSendRecord.isPresent() ? smsSendRecord.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateSmsSendRecord(SmsSendRecordUpdater updater) {
    EntityOperations.doUpdate(smsSendRecordRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateSmsSendRecord(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validSmsSendRecord(Long id) {
    EntityOperations.doUpdate(smsSendRecordRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidSmsSendRecord(Long id) {
    EntityOperations.doUpdate(smsSendRecordRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public SmsSendRecordVO findById(Long id) {
    Optional<SmsSendRecord> smsSendRecord =  smsSendRecordRepository.findById(id);
    return new SmsSendRecordVO(smsSendRecord.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<SmsSendRecordVO> findByPage(PageRequestWrapper<SmsSendRecordQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<SmsSendRecord> page = smsSendRecordRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new SmsSendRecordVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
