// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.user.UserAccount;
import java.lang.Long;

public interface UserAccountRepository extends BaseRepository<UserAccount, Long> {
}
