// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.user.UserBase;
import java.lang.Long;

public interface UserBaseRepository extends BaseRepository<UserBase, Long> {
}
