// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.asset.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class AssetQueryRequest implements Request {
}
