// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.asset.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
@Data
public class AssetCreateRequest implements Request {
  @Schema(
      title = "仓库id"
  )
  private Long houseId;

  @Schema(
      title = "资产名称"
  )
  private String name;

  @Schema(
      title = "唯一编码列表"
  )
  private List<String> uniqueCodes;

  @Schema(
      title = "skuId"
  )
  private Long skuId;

  @Schema(
          title = "批次号"
  )
  private String batchNo;

}
