// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.warehouse.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.asset.warehouse.Warehouse;
import java.lang.Long;

public interface WarehouseRepository extends BaseRepository<Warehouse, Long> {
}
