// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.user.UserBase;
import com.only4play.system.domain.user.creator.UserBaseCreator;
import com.only4play.system.domain.user.query.UserBaseQuery;
import com.only4play.system.domain.user.request.UserBaseCreateRequest;
import com.only4play.system.domain.user.request.UserBaseQueryRequest;
import com.only4play.system.domain.user.request.UserBaseUpdateRequest;
import com.only4play.system.domain.user.response.UserBaseResponse;
import com.only4play.system.domain.user.updater.UserBaseUpdater;
import com.only4play.system.domain.user.vo.UserBaseVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface UserBaseMapper {
  UserBaseMapper INSTANCE = Mappers.getMapper(UserBaseMapper.class);

  UserBase dtoToEntity(UserBaseCreator dto);

  UserBaseUpdater request2Updater(UserBaseUpdateRequest request);

  UserBaseCreator request2Dto(UserBaseCreateRequest request);

  UserBaseQuery request2Query(UserBaseQueryRequest request);

  UserBaseResponse vo2Response(UserBaseVO vo);

  default UserBaseResponse vo2CustomResponse(UserBaseVO vo) {
    UserBaseResponse response = vo2Response(vo);
    return response;
  }
}
