// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.user.UserAccount;
import com.only4play.system.domain.user.creator.UserAccountCreator;
import com.only4play.system.domain.user.query.UserAccountQuery;
import com.only4play.system.domain.user.request.UserAccountCreateRequest;
import com.only4play.system.domain.user.request.UserAccountQueryRequest;
import com.only4play.system.domain.user.request.UserAccountUpdateRequest;
import com.only4play.system.domain.user.response.UserAccountResponse;
import com.only4play.system.domain.user.updater.UserAccountUpdater;
import com.only4play.system.domain.user.vo.UserAccountVO;
import com.only4play.system.infrastructure.converter.CustomMapper;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class,
        CustomMapper.class
    }
)
public interface UserAccountMapper {
  UserAccountMapper INSTANCE = Mappers.getMapper(UserAccountMapper.class);

  UserAccount dtoToEntity(UserAccountCreator dto);

  UserAccountUpdater request2Updater(UserAccountUpdateRequest request);

  UserAccountCreator request2Dto(UserAccountCreateRequest request);

  UserAccountQuery request2Query(UserAccountQueryRequest request);

  UserAccountResponse vo2Response(UserAccountVO vo);

  default UserAccountResponse vo2CustomResponse(UserAccountVO vo) {
    UserAccountResponse response = vo2Response(vo);
    return response;
  }
}
