// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.platform.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.permission.platform.Platform;
import com.only4play.system.domain.permission.platform.creator.PlatformCreator;
import com.only4play.system.domain.permission.platform.query.PlatformQuery;
import com.only4play.system.domain.permission.platform.request.PlatformCreateRequest;
import com.only4play.system.domain.permission.platform.request.PlatformQueryRequest;
import com.only4play.system.domain.permission.platform.request.PlatformUpdateRequest;
import com.only4play.system.domain.permission.platform.response.PlatformResponse;
import com.only4play.system.domain.permission.platform.updater.PlatformUpdater;
import com.only4play.system.domain.permission.platform.vo.PlatformVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface PlatformMapper {
  PlatformMapper INSTANCE = Mappers.getMapper(PlatformMapper.class);

  Platform dtoToEntity(PlatformCreator dto);

  PlatformUpdater request2Updater(PlatformUpdateRequest request);

  PlatformCreator request2Dto(PlatformCreateRequest request);

  PlatformQuery request2Query(PlatformQueryRequest request);

  PlatformResponse vo2Response(PlatformVO vo);

  default PlatformResponse vo2CustomResponse(PlatformVO vo) {
    PlatformResponse response = vo2Response(vo);
    return response;
  }
}
