// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.payitemconfig.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.payitemconfig.PayItemConfig;
import java.lang.Long;
import java.util.List;

public interface PayItemConfigRepository extends BaseRepository<PayItemConfig, Long> {

  List<PayItemConfig> findPayItemConfigsByTradeTypeCode(String tradeTypeCode);
}
