// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.admin.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.admin.AdminUser;
import java.lang.Long;
import java.util.Optional;

public interface AdminUserRepository extends BaseRepository<AdminUser, Long> {

  Optional<AdminUser> findByPhone(String phone);
}
