// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.reviserecord.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.trade.reviserecord.creator.ReviseRecordCreator;
import com.only4play.system.domain.trade.reviserecord.query.ReviseRecordQuery;
import com.only4play.system.domain.trade.reviserecord.updater.ReviseRecordUpdater;
import com.only4play.system.domain.trade.reviserecord.vo.ReviseRecordVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IReviseRecordService {
  /**
   * create
   */
  Long createReviseRecord(ReviseRecordCreator creator);

  /**
   * update
   */
  void updateReviseRecord(ReviseRecordUpdater updater);

  /**
   * valid
   */
  void validReviseRecord(Long id);

  /**
   * invalid
   */
  void invalidReviseRecord(Long id);

  /**
   * findById
   */
  ReviseRecordVO findById(Long id);

  /**
   * findByPage
   */
  Page<ReviseRecordVO> findByPage(PageRequestWrapper<ReviseRecordQuery> query);
}
