// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.enterpriseentity.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.invoice.enterpriseentity.EnterpriseEntity;
import com.only4play.system.domain.invoice.enterpriseentity.creator.EnterpriseEntityCreator;
import com.only4play.system.domain.invoice.enterpriseentity.mapper.EnterpriseEntityMapper;
import com.only4play.system.domain.invoice.enterpriseentity.query.EnterpriseEntityQuery;
import com.only4play.system.domain.invoice.enterpriseentity.repository.EnterpriseEntityRepository;
import com.only4play.system.domain.invoice.enterpriseentity.updater.EnterpriseEntityUpdater;
import com.only4play.system.domain.invoice.enterpriseentity.vo.EnterpriseEntityVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class EnterpriseEntityServiceImpl implements IEnterpriseEntityService {
  private final EnterpriseEntityRepository enterpriseEntityRepository;

  /**
   * createImpl
   */
  @Override
  public Long createEnterpriseEntity(EnterpriseEntityCreator creator) {
    Optional<EnterpriseEntity> enterpriseEntity = EntityOperations.doCreate(enterpriseEntityRepository)
    .create(() -> EnterpriseEntityMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return enterpriseEntity.isPresent() ? enterpriseEntity.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateEnterpriseEntity(EnterpriseEntityUpdater updater) {
    EntityOperations.doUpdate(enterpriseEntityRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateEnterpriseEntity(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validEnterpriseEntity(Long id) {
    EntityOperations.doUpdate(enterpriseEntityRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidEnterpriseEntity(Long id) {
    EntityOperations.doUpdate(enterpriseEntityRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public EnterpriseEntityVO findById(Long id) {
    Optional<EnterpriseEntity> enterpriseEntity =  enterpriseEntityRepository.findById(id);
    return new EnterpriseEntityVO(enterpriseEntity.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  @Override
  public EnterpriseEntityVO findByTaxCode(String taxCode) {
    Optional<EnterpriseEntity> enterpriseEntity =  enterpriseEntityRepository.findByTaxCode(taxCode);
    return new EnterpriseEntityVO(enterpriseEntity.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<EnterpriseEntityVO> findByPage(PageRequestWrapper<EnterpriseEntityQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<EnterpriseEntity> page = enterpriseEntityRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new EnterpriseEntityVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
