// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.enterpriseentity.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.invoice.enterpriseentity.creator.EnterpriseEntityCreator;
import com.only4play.system.domain.invoice.enterpriseentity.query.EnterpriseEntityQuery;
import com.only4play.system.domain.invoice.enterpriseentity.updater.EnterpriseEntityUpdater;
import com.only4play.system.domain.invoice.enterpriseentity.vo.EnterpriseEntityVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IEnterpriseEntityService {
  /**
   * create
   */
  Long createEnterpriseEntity(EnterpriseEntityCreator creator);

  /**
   * update
   */
  void updateEnterpriseEntity(EnterpriseEntityUpdater updater);

  /**
   * valid
   */
  void validEnterpriseEntity(Long id);

  /**
   * invalid
   */
  void invalidEnterpriseEntity(Long id);

  /**
   * findById
   */
  EnterpriseEntityVO findById(Long id);

  /**
   * 根据税务编码查询企业信息
   * @param taxCode
   * @return
   */
  EnterpriseEntityVO findByTaxCode(String taxCode);

  /**
   * findByPage
   */
  Page<EnterpriseEntityVO> findByPage(PageRequestWrapper<EnterpriseEntityQuery> query);
}
