// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.assetrecord.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.asset.assetrecord.AssetInOutRecord;
import java.lang.Long;

public interface AssetInOutRecordRepository extends BaseRepository<AssetInOutRecord, Long> {
}
