// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.objectsku.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.objectsku.creator.ObjectSkuCreator;
import com.only4play.system.domain.objectsku.query.ObjectSkuQuery;
import com.only4play.system.domain.objectsku.updater.ObjectSkuUpdater;
import com.only4play.system.domain.objectsku.vo.ObjectSkuVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IObjectSkuService {
  /**
   * create
   */
  Long createObjectSku(ObjectSkuCreator creator);

  /**
   * update
   */
  void updateObjectSku(ObjectSkuUpdater updater);

  /**
   * valid
   */
  void validObjectSku(Long id);

  /**
   * invalid
   */
  void invalidObjectSku(Long id);

  /**
   * findById
   */
  ObjectSkuVO findById(Long id);

  /**
   * findByPage
   */
  Page<ObjectSkuVO> findByPage(PageRequestWrapper<ObjectSkuQuery> query);
}
