// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.objectsku.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.objectsku.creator.SkuAttributeCreator;
import com.only4play.system.domain.objectsku.query.SkuAttributeQuery;
import com.only4play.system.domain.objectsku.updater.SkuAttributeUpdater;
import com.only4play.system.domain.objectsku.vo.SkuAttributeVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ISkuAttributeService {
  /**
   * create
   */
  Long createSkuAttribute(SkuAttributeCreator creator);

  /**
   * update
   */
  void updateSkuAttribute(SkuAttributeUpdater updater);

  /**
   * valid
   */
  void validSkuAttribute(Long id);

  /**
   * invalid
   */
  void invalidSkuAttribute(Long id);

  /**
   * findById
   */
  SkuAttributeVO findById(Long id);

  /**
   * findByPage
   */
  Page<SkuAttributeVO> findByPage(PageRequestWrapper<SkuAttributeQuery> query);
}
