// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.objectsku.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.objectsku.ObjectSku;
import com.only4play.system.domain.objectsku.creator.ObjectSkuCreator;
import com.only4play.system.domain.objectsku.mapper.ObjectSkuMapper;
import com.only4play.system.domain.objectsku.query.ObjectSkuQuery;
import com.only4play.system.domain.objectsku.repository.ObjectSkuRepository;
import com.only4play.system.domain.objectsku.updater.ObjectSkuUpdater;
import com.only4play.system.domain.objectsku.vo.ObjectSkuVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ObjectSkuServiceImpl implements IObjectSkuService {
  private final ObjectSkuRepository objectSkuRepository;

  /**
   * createImpl
   */
  @Override
  public Long createObjectSku(ObjectSkuCreator creator) {
    Optional<ObjectSku> objectSku = EntityOperations.doCreate(objectSkuRepository)
    .create(() -> ObjectSkuMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return objectSku.isPresent() ? objectSku.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateObjectSku(ObjectSkuUpdater updater) {
    EntityOperations.doUpdate(objectSkuRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateObjectSku(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validObjectSku(Long id) {
    EntityOperations.doUpdate(objectSkuRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidObjectSku(Long id) {
    EntityOperations.doUpdate(objectSkuRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public ObjectSkuVO findById(Long id) {
    Optional<ObjectSku> objectSku =  objectSkuRepository.findById(id);
    return new ObjectSkuVO(objectSku.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<ObjectSkuVO> findByPage(PageRequestWrapper<ObjectSkuQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<ObjectSku> page = objectSkuRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new ObjectSkuVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
