// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.objectsku.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.objectsku.SkuAttribute;
import com.only4play.system.domain.objectsku.creator.SkuAttributeCreator;
import com.only4play.system.domain.objectsku.mapper.SkuAttributeMapper;
import com.only4play.system.domain.objectsku.query.SkuAttributeQuery;
import com.only4play.system.domain.objectsku.repository.SkuAttributeRepository;
import com.only4play.system.domain.objectsku.updater.SkuAttributeUpdater;
import com.only4play.system.domain.objectsku.vo.SkuAttributeVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class SkuAttributeServiceImpl implements ISkuAttributeService {
  private final SkuAttributeRepository skuAttributeRepository;

  /**
   * createImpl
   */
  @Override
  public Long createSkuAttribute(SkuAttributeCreator creator) {
    Optional<SkuAttribute> skuAttribute = EntityOperations.doCreate(skuAttributeRepository)
    .create(() -> SkuAttributeMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return skuAttribute.isPresent() ? skuAttribute.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateSkuAttribute(SkuAttributeUpdater updater) {
    EntityOperations.doUpdate(skuAttributeRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateSkuAttribute(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validSkuAttribute(Long id) {
    EntityOperations.doUpdate(skuAttributeRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidSkuAttribute(Long id) {
    EntityOperations.doUpdate(skuAttributeRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public SkuAttributeVO findById(Long id) {
    Optional<SkuAttribute> skuAttribute =  skuAttributeRepository.findById(id);
    return new SkuAttributeVO(skuAttribute.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<SkuAttributeVO> findByPage(PageRequestWrapper<SkuAttributeQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<SkuAttribute> page = skuAttributeRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new SkuAttributeVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
