// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.invoice.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.invoice.invoice.creator.InvoiceCreator;
import com.only4play.system.domain.invoice.invoice.query.InvoiceQuery;
import com.only4play.system.domain.invoice.invoice.updater.InvoiceUpdater;
import com.only4play.system.domain.invoice.invoice.vo.InvoiceVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IInvoiceService {
  /**
   * create
   */
  Long createInvoice(InvoiceCreator creator);

  /**
   * update
   */
  void updateInvoice(InvoiceUpdater updater);

  /**
   * valid
   */
  void validInvoice(Long id);

  /**
   * invalid
   */
  void invalidInvoice(Long id);

  /**
   * findById
   */
  InvoiceVO findById(Long id);

  /**
   * findByPage
   */
  Page<InvoiceVO> findByPage(PageRequestWrapper<InvoiceQuery> query);
}
