// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.invoice.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.invoice.invoice.Invoice;
import com.only4play.system.domain.invoice.invoice.creator.InvoiceCreator;
import com.only4play.system.domain.invoice.invoice.mapper.InvoiceMapper;
import com.only4play.system.domain.invoice.invoice.query.InvoiceQuery;
import com.only4play.system.domain.invoice.invoice.repository.InvoiceRepository;
import com.only4play.system.domain.invoice.invoice.updater.InvoiceUpdater;
import com.only4play.system.domain.invoice.invoice.vo.InvoiceVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class InvoiceServiceImpl implements IInvoiceService {
  private final InvoiceRepository invoiceRepository;

  /**
   * createImpl
   */
  @Override
  public Long createInvoice(InvoiceCreator creator) {
    Optional<Invoice> invoice = EntityOperations.doCreate(invoiceRepository)
    .create(() -> InvoiceMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return invoice.isPresent() ? invoice.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateInvoice(InvoiceUpdater updater) {
    EntityOperations.doUpdate(invoiceRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateInvoice(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validInvoice(Long id) {
    EntityOperations.doUpdate(invoiceRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidInvoice(Long id) {
    EntityOperations.doUpdate(invoiceRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public InvoiceVO findById(Long id) {
    Optional<Invoice> invoice =  invoiceRepository.findById(id);
    return new InvoiceVO(invoice.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<InvoiceVO> findByPage(PageRequestWrapper<InvoiceQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<Invoice> page = invoiceRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new InvoiceVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
