// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.orderitem.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;

@Schema
public class OrderItemUpdateRequest implements Request {
  @Schema(
      title = "唯一流水号"
  )
  private Long flowNo;

  @Schema(
      title = "amount"
  )
  private BigDecimal amount;

  @Schema(
      title = "真实金额"
  )
  private BigDecimal realAmount;

  @Schema(
      title = "计量数量"
  )
  private BigDecimal itemCount;

  @Schema(
      title = "计量单位"
  )
  private String measureUnit;

  @Schema(
      title = "商品ID/计费模型ID"
  )
  private String goodsId;

  @Schema(
      title = "商品编码"
  )
  private String goodsCode;

  @Schema(
      title = "商品名称"
  )
  private String goodsName;

  @Schema(
      title = "费用描述"
  )
  private String feeRemark;

  private Long id;

  public Long getFlowNo() {
    return flowNo;
  }

  public void setFlowNo(Long flowNo) {
    this.flowNo = flowNo;
  }

  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public BigDecimal getRealAmount() {
    return realAmount;
  }

  public void setRealAmount(BigDecimal realAmount) {
    this.realAmount = realAmount;
  }

  public BigDecimal getItemCount() {
    return itemCount;
  }

  public void setItemCount(BigDecimal itemCount) {
    this.itemCount = itemCount;
  }

  public String getMeasureUnit() {
    return measureUnit;
  }

  public void setMeasureUnit(String measureUnit) {
    this.measureUnit = measureUnit;
  }

  public String getGoodsId() {
    return goodsId;
  }

  public void setGoodsId(String goodsId) {
    this.goodsId = goodsId;
  }

  public String getGoodsCode() {
    return goodsCode;
  }

  public void setGoodsCode(String goodsCode) {
    this.goodsCode = goodsCode;
  }

  public String getGoodsName() {
    return goodsName;
  }

  public void setGoodsName(String goodsName) {
    this.goodsName = goodsName;
  }

  public String getFeeRemark() {
    return feeRemark;
  }

  public void setFeeRemark(String feeRemark) {
    this.feeRemark = feeRemark;
  }

  public Long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }
}
