// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.taxrateconfig.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.taxrateconfig.TaxRateConfig;
import java.lang.Long;
import java.util.Optional;

public interface TaxRateConfigRepository extends BaseRepository<TaxRateConfig, Long> {

  /**
   * 确定数据库最多只能存在一条时，返回optional
   * @param taxCategoryCode
   * @return
   */
  Optional<TaxRateConfig> findByTaxCategoryCode(String taxCategoryCode);
}
