// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.templateitem.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.template.templateitem.TemplateItem;
import java.lang.Long;

public interface TemplateItemRepository extends BaseRepository<TemplateItem, Long> {
}
