// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.templateitem.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.template.templateitem.TemplateItem;
import com.only4play.system.domain.template.templateitem.creator.TemplateItemCreator;
import com.only4play.system.domain.template.templateitem.query.TemplateItemQuery;
import com.only4play.system.domain.template.templateitem.request.TemplateItemCreateRequest;
import com.only4play.system.domain.template.templateitem.request.TemplateItemQueryRequest;
import com.only4play.system.domain.template.templateitem.request.TemplateItemUpdateRequest;
import com.only4play.system.domain.template.templateitem.response.TemplateItemResponse;
import com.only4play.system.domain.template.templateitem.updater.TemplateItemUpdater;
import com.only4play.system.domain.template.templateitem.vo.TemplateItemVO;
import com.only4play.system.infrastructure.converter.CustomMapper;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class,
        CustomMapper.class
    }
)
public interface TemplateItemMapper {
  TemplateItemMapper INSTANCE = Mappers.getMapper(TemplateItemMapper.class);

  TemplateItem dtoToEntity(TemplateItemCreator dto);

  TemplateItemUpdater request2Updater(TemplateItemUpdateRequest request);

  TemplateItemCreator request2Dto(TemplateItemCreateRequest request);

  TemplateItemQuery request2Query(TemplateItemQueryRequest request);

  TemplateItemResponse vo2Response(TemplateItemVO vo);

  default TemplateItemResponse vo2CustomResponse(TemplateItemVO vo) {
    TemplateItemResponse response = vo2Response(vo);
    return response;
  }
}
