// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.orderlifecycle.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.trade.orderlifecycle.OrderLifecycle;
import java.lang.Long;

public interface OrderLifecycleRepository extends BaseRepository<OrderLifecycle, Long> {
}
