// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.asset.assetrecord.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.asset.assetrecord.AssetInOutRecord;
import com.only4play.system.domain.asset.assetrecord.creator.AssetInOutRecordCreator;
import com.only4play.system.domain.asset.assetrecord.query.AssetInOutRecordQuery;
import com.only4play.system.domain.asset.assetrecord.request.AssetInOutRecordCreateRequest;
import com.only4play.system.domain.asset.assetrecord.request.AssetInOutRecordQueryRequest;
import com.only4play.system.domain.asset.assetrecord.request.AssetInOutRecordUpdateRequest;
import com.only4play.system.domain.asset.assetrecord.response.AssetInOutRecordResponse;
import com.only4play.system.domain.asset.assetrecord.updater.AssetInOutRecordUpdater;
import com.only4play.system.domain.asset.assetrecord.vo.AssetInOutRecordVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface AssetInOutRecordMapper {
  AssetInOutRecordMapper INSTANCE = Mappers.getMapper(AssetInOutRecordMapper.class);

  AssetInOutRecord dtoToEntity(AssetInOutRecordCreator dto);

  AssetInOutRecordUpdater request2Updater(AssetInOutRecordUpdateRequest request);

  AssetInOutRecordCreator request2Dto(AssetInOutRecordCreateRequest request);

  AssetInOutRecordQuery request2Query(AssetInOutRecordQueryRequest request);

  AssetInOutRecordResponse vo2Response(AssetInOutRecordVO vo);

  default AssetInOutRecordResponse vo2CustomResponse(AssetInOutRecordVO vo) {
    AssetInOutRecordResponse response = vo2Response(vo);
    return response;
  }
}
