// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.role.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.permission.role.RoleResourceRel;
import java.lang.Long;

public interface RoleResourceRelRepository extends BaseRepository<RoleResourceRel, Long> {
}
