// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.role.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.permission.role.Role;
import java.lang.Long;

public interface RoleRepository extends BaseRepository<Role, Long> {
}
