// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.orderitem.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.trade.orderitem.creator.OrderItemCreator;
import com.only4play.system.domain.trade.orderitem.query.OrderItemQuery;
import com.only4play.system.domain.trade.orderitem.updater.OrderItemUpdater;
import com.only4play.system.domain.trade.orderitem.vo.OrderItemVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IOrderItemService {
  /**
   * create
   */
  Long createOrderItem(OrderItemCreator creator);

  /**
   * update
   */
  void updateOrderItem(OrderItemUpdater updater);

  /**
   * findById
   */
  OrderItemVO findById(Long id);

  /**
   * findByPage
   */
  Page<OrderItemVO> findByPage(PageRequestWrapper<OrderItemQuery> query);
}
