// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.selectdict.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.template.selectdict.creator.SelectDictCreator;
import com.only4play.system.domain.template.selectdict.query.SelectDictQuery;
import com.only4play.system.domain.template.selectdict.updater.SelectDictUpdater;
import com.only4play.system.domain.template.selectdict.vo.SelectDictVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ISelectDictService {
  /**
   * create
   */
  Long createSelectDict(SelectDictCreator creator);

  /**
   * update
   */
  void updateSelectDict(SelectDictUpdater updater);

  /**
   * valid
   */
  void validSelectDict(Long id);

  /**
   * invalid
   */
  void invalidSelectDict(Long id);

  /**
   * findById
   */
  SelectDictVO findById(Long id);

  /**
   * findByPage
   */
  Page<SelectDictVO> findByPage(PageRequestWrapper<SelectDictQuery> query);
}
