// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.objecttemplate.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.template.objecttemplate.creator.TemplateCategoryCreator;
import com.only4play.system.domain.template.objecttemplate.query.TemplateCategoryQuery;
import com.only4play.system.domain.template.objecttemplate.updater.TemplateCategoryUpdater;
import com.only4play.system.domain.template.objecttemplate.vo.TemplateCategoryVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ITemplateCategoryService {
  /**
   * create
   */
  Long createTemplateCategory(TemplateCategoryCreator creator);

  /**
   * update
   */
  void updateTemplateCategory(TemplateCategoryUpdater updater);

  /**
   * valid
   */
  void validTemplateCategory(Long id);

  /**
   * invalid
   */
  void invalidTemplateCategory(Long id);

  /**
   * findById
   */
  TemplateCategoryVO findById(Long id);

  /**
   * findByPage
   */
  Page<TemplateCategoryVO> findByPage(PageRequestWrapper<TemplateCategoryQuery> query);
}
