// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.objecttemplate.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.template.objecttemplate.ObjectTemplate;
import com.only4play.system.domain.template.objecttemplate.creator.ObjectTemplateCreator;
import com.only4play.system.domain.template.objecttemplate.mapper.ObjectTemplateMapper;
import com.only4play.system.domain.template.objecttemplate.query.ObjectTemplateQuery;
import com.only4play.system.domain.template.objecttemplate.repository.ObjectTemplateRepository;
import com.only4play.system.domain.template.objecttemplate.updater.ObjectTemplateUpdater;
import com.only4play.system.domain.template.objecttemplate.vo.ObjectTemplateVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ObjectTemplateServiceImpl implements IObjectTemplateService {
  private final ObjectTemplateRepository objectTemplateRepository;

  /**
   * createImpl
   */
  @Override
  public Long createObjectTemplate(ObjectTemplateCreator creator) {
    Optional<ObjectTemplate> objectTemplate = EntityOperations.doCreate(objectTemplateRepository)
    .create(() -> ObjectTemplateMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return objectTemplate.isPresent() ? objectTemplate.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateObjectTemplate(ObjectTemplateUpdater updater) {
    EntityOperations.doUpdate(objectTemplateRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateObjectTemplate(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validObjectTemplate(Long id) {
    EntityOperations.doUpdate(objectTemplateRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidObjectTemplate(Long id) {
    EntityOperations.doUpdate(objectTemplateRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public ObjectTemplateVO findById(Long id) {
    Optional<ObjectTemplate> objectTemplate =  objectTemplateRepository.findById(id);
    return new ObjectTemplateVO(objectTemplate.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<ObjectTemplateVO> findByPage(PageRequestWrapper<ObjectTemplateQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<ObjectTemplate> page = objectTemplateRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new ObjectTemplateVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
