// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.response;

import com.only4play.common.constants.ValidStatus;
import com.only4play.common.model.AbstractJpaResponse;
import com.only4play.system.domain.user.AccountType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class UserAccountResponse extends AbstractJpaResponse {
  @Schema(
      title = "用户ID"
  )
  private Long userId;

  @Schema(
      title = "账号"
  )
  private String accountNo;

  @Schema(
      title = "密码"
  )
  private String password;

  @Schema(
      title = "账号类型"
  )
  private AccountType accountType;

  @Schema(
      title = "validStatus"
  )
  private ValidStatus validStatus;

  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public String getAccountNo() {
    return accountNo;
  }

  public void setAccountNo(String accountNo) {
    this.accountNo = accountNo;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public AccountType getAccountType() {
    return accountType;
  }

  public void setAccountType(AccountType accountType) {
    this.accountType = accountType;
  }

  public ValidStatus getValidStatus() {
    return validStatus;
  }

  public void setValidStatus(ValidStatus validStatus) {
    this.validStatus = validStatus;
  }
}
