// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.user.response;

import com.only4play.common.constants.ValidStatus;
import com.only4play.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class UserBaseResponse extends AbstractJpaResponse {
  @Schema(
      title = "uuid"
  )
  private String uuid;

  @Schema(
      title = "phone"
  )
  private String phone;

  @Schema(
      title = "validStatus"
  )
  private ValidStatus validStatus;

  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public ValidStatus getValidStatus() {
    return validStatus;
  }

  public void setValidStatus(ValidStatus validStatus) {
    this.validStatus = validStatus;
  }
}
