// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.reviserecord.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.trade.reviserecord.ReviseRecord;
import java.lang.Long;

public interface ReviseRecordRepository extends BaseRepository<ReviseRecord, Long> {
}
