// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.request;

import com.only4play.common.model.Request;
import com.only4play.order.commons.pay.PayItem;
import com.only4play.system.infrastructure.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;
import java.util.List;

@Schema
public class OrderReceiptUpdateRequest implements Request {
  @Schema(
      title = "注册流水号"
  )
  private Long registerFlowNo;

  @Schema(
      title = "业务系统编码"
  )
  private String bizSystemCode;

  @Schema(
      title = "交易类型编码"
  )
  private String tradeTypeCode;

  @Schema(
      title = "交易类型名称"
  )
  private String tradeTypeName;

  @Schema(
      title = "订单属性"
  )
  private List<CodeValue> orderAttrs;

  @Schema(
      title = "开票金额"
  )
  private BigDecimal makeOutAmount;

  @Schema(
      title = "不可开票金额"
  )
  private BigDecimal unMakeOutAmount;

  @Schema(
      title = "可用开票明细"
  )
  private List<PayItem> validList;

  @Schema(
      title = "不可用开票明细"
  )
  private List<PayItem> invalidList;

  private Long id;

  public Long getRegisterFlowNo() {
    return registerFlowNo;
  }

  public void setRegisterFlowNo(Long registerFlowNo) {
    this.registerFlowNo = registerFlowNo;
  }

  public String getBizSystemCode() {
    return bizSystemCode;
  }

  public void setBizSystemCode(String bizSystemCode) {
    this.bizSystemCode = bizSystemCode;
  }

  public String getTradeTypeCode() {
    return tradeTypeCode;
  }

  public void setTradeTypeCode(String tradeTypeCode) {
    this.tradeTypeCode = tradeTypeCode;
  }

  public String getTradeTypeName() {
    return tradeTypeName;
  }

  public void setTradeTypeName(String tradeTypeName) {
    this.tradeTypeName = tradeTypeName;
  }

  public List<CodeValue> getOrderAttrs() {
    return orderAttrs;
  }

  public void setOrderAttrs(List<CodeValue> orderAttrs) {
    this.orderAttrs = orderAttrs;
  }

  public BigDecimal getMakeOutAmount() {
    return makeOutAmount;
  }

  public void setMakeOutAmount(BigDecimal makeOutAmount) {
    this.makeOutAmount = makeOutAmount;
  }

  public BigDecimal getUnMakeOutAmount() {
    return unMakeOutAmount;
  }

  public void setUnMakeOutAmount(BigDecimal unMakeOutAmount) {
    this.unMakeOutAmount = unMakeOutAmount;
  }

  public List<PayItem> getValidList() {
    return validList;
  }

  public void setValidList(List<PayItem> validList) {
    this.validList = validList;
  }

  public List<PayItem> getInvalidList() {
    return invalidList;
  }

  public void setInvalidList(List<PayItem> invalidList) {
    this.invalidList = invalidList;
  }

  public Long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }
}
