// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.orderreceipt.OrderReceipt;
import java.lang.Long;
import java.util.List;
import java.util.Optional;

public interface OrderReceiptRepository extends BaseRepository<OrderReceipt, Long> {

  Optional<OrderReceipt> findByRegisterFlowNo(Long flowNo);

  List<OrderReceipt> findAllByRegisterFlowNoIn(List<Long> flowNos);
}
