// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.orderreceipt.ReceiptItem;
import java.lang.Long;

public interface ReceiptItemRepository extends BaseRepository<ReceiptItem, Long> {
}
