// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.orderreceipt.ReceiptInvoiceRel;
import java.lang.Long;

public interface ReceiptInvoiceRelRepository extends BaseRepository<ReceiptInvoiceRel, Long> {
}
