// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.orderitem.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.trade.orderitem.OrderItem;
import java.lang.Long;

public interface OrderItemRepository extends BaseRepository<OrderItem, Long> {
}
