// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.resource.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.permission.resource.Resource;
import java.lang.Long;

public interface ResourceRepository extends BaseRepository<Resource, Long> {
}
