// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.taxrateconfig.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.invoice.taxrateconfig.TaxRateConfig;
import com.only4play.system.domain.invoice.taxrateconfig.creator.TaxRateConfigCreator;
import com.only4play.system.domain.invoice.taxrateconfig.mapper.TaxRateConfigMapper;
import com.only4play.system.domain.invoice.taxrateconfig.query.TaxRateConfigQuery;
import com.only4play.system.domain.invoice.taxrateconfig.repository.TaxRateConfigRepository;
import com.only4play.system.domain.invoice.taxrateconfig.updater.TaxRateConfigUpdater;
import com.only4play.system.domain.invoice.taxrateconfig.vo.TaxRateConfigVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class TaxRateConfigServiceImpl implements ITaxRateConfigService {
  private final TaxRateConfigRepository taxRateConfigRepository;

  /**
   * createImpl
   */
  @Override
  public Long createTaxRateConfig(TaxRateConfigCreator creator) {
    Optional<TaxRateConfig> taxRateConfig = EntityOperations.doCreate(taxRateConfigRepository)
    .create(() -> TaxRateConfigMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return taxRateConfig.isPresent() ? taxRateConfig.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateTaxRateConfig(TaxRateConfigUpdater updater) {
    EntityOperations.doUpdate(taxRateConfigRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateTaxRateConfig(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validTaxRateConfig(Long id) {
    EntityOperations.doUpdate(taxRateConfigRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidTaxRateConfig(Long id) {
    EntityOperations.doUpdate(taxRateConfigRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public TaxRateConfigVO findById(Long id) {
    Optional<TaxRateConfig> taxRateConfig =  taxRateConfigRepository.findById(id);
    return new TaxRateConfigVO(taxRateConfig.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<TaxRateConfigVO> findByPage(PageRequestWrapper<TaxRateConfigQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<TaxRateConfig> page = taxRateConfigRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new TaxRateConfigVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
