// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.objectsku.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.objectsku.SkuAttribute;
import com.only4play.system.domain.objectsku.creator.SkuAttributeCreator;
import com.only4play.system.domain.objectsku.query.SkuAttributeQuery;
import com.only4play.system.domain.objectsku.request.SkuAttributeCreateRequest;
import com.only4play.system.domain.objectsku.request.SkuAttributeQueryRequest;
import com.only4play.system.domain.objectsku.request.SkuAttributeUpdateRequest;
import com.only4play.system.domain.objectsku.response.SkuAttributeResponse;
import com.only4play.system.domain.objectsku.updater.SkuAttributeUpdater;
import com.only4play.system.domain.objectsku.vo.SkuAttributeVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface SkuAttributeMapper {
  SkuAttributeMapper INSTANCE = Mappers.getMapper(SkuAttributeMapper.class);

  SkuAttribute dtoToEntity(SkuAttributeCreator dto);

  SkuAttributeUpdater request2Updater(SkuAttributeUpdateRequest request);

  SkuAttributeCreator request2Dto(SkuAttributeCreateRequest request);

  SkuAttributeQuery request2Query(SkuAttributeQueryRequest request);

  SkuAttributeResponse vo2Response(SkuAttributeVO vo);

  default SkuAttributeResponse vo2CustomResponse(SkuAttributeVO vo) {
    SkuAttributeResponse response = vo2Response(vo);
    return response;
  }
}
