// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.platform.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.permission.platform.Platform;
import java.lang.Long;

public interface PlatformRepository extends BaseRepository<Platform, Long> {
}
