// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.trade.order.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.trade.order.OrderBase;
import com.only4play.system.domain.trade.order.creator.OrderBaseCreator;
import com.only4play.system.domain.trade.order.mapper.OrderBaseMapper;
import com.only4play.system.domain.trade.order.query.OrderBaseQuery;
import com.only4play.system.domain.trade.order.repository.OrderBaseRepository;
import com.only4play.system.domain.trade.order.updater.OrderBaseUpdater;
import com.only4play.system.domain.trade.order.vo.OrderBaseVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class OrderBaseServiceImpl implements IOrderBaseService {
  private final OrderBaseRepository orderBaseRepository;

  /**
   * createImpl
   */
  @Override
  public Long createOrderBase(OrderBaseCreator creator) {
    return 0L;
  }

  /**
   * update
   */
  @Override
  public void updateOrderBase(OrderBaseUpdater updater) {
    EntityOperations.doUpdate(orderBaseRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateOrderBase(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validOrderBase(Long id) {
    EntityOperations.doUpdate(orderBaseRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidOrderBase(Long id) {
    EntityOperations.doUpdate(orderBaseRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public OrderBaseVO findById(Long id) {
    Optional<OrderBase> orderBase =  orderBaseRepository.findById(id);
    return new OrderBaseVO(orderBase.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<OrderBaseVO> findByPage(PageRequestWrapper<OrderBaseQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<OrderBase> page = orderBaseRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new OrderBaseVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
