// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.enterpriserouter.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.invoice.enterpriserouter.EnterpriseRouter;
import java.lang.Long;

public interface EnterpriseRouterRepository extends BaseRepository<EnterpriseRouter, Long> {
}
