// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.invoice.orderreceipt.OrderReceipt;
import com.only4play.system.domain.invoice.orderreceipt.creator.OrderReceiptCreator;
import com.only4play.system.domain.invoice.orderreceipt.domainservice.model.register.OrderRegisterModel;
import com.only4play.system.domain.invoice.orderreceipt.query.OrderReceiptQuery;
import com.only4play.system.domain.invoice.orderreceipt.request.OrderReceiptCreateRequest;
import com.only4play.system.domain.invoice.orderreceipt.request.OrderReceiptQueryRequest;
import com.only4play.system.domain.invoice.orderreceipt.request.OrderReceiptUpdateRequest;
import com.only4play.system.domain.invoice.orderreceipt.response.OrderReceiptResponse;
import com.only4play.system.domain.invoice.orderreceipt.updater.OrderReceiptUpdater;
import com.only4play.system.domain.invoice.orderreceipt.vo.OrderReceiptVO;
import com.only4play.system.infrastructure.converter.CustomMapper;
import com.only4play.system.infrastructure.elastic.OrderReceiptDocument;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class,
        CustomMapper.class
    }
)
public interface OrderReceiptMapper {
  OrderReceiptMapper INSTANCE = Mappers.getMapper(OrderReceiptMapper.class);

  OrderReceipt dtoToEntity(OrderReceiptCreator dto);

  OrderReceiptUpdater request2Updater(OrderReceiptUpdateRequest request);

  OrderReceiptCreator request2Dto(OrderReceiptCreateRequest request);

  OrderReceiptQuery request2Query(OrderReceiptQueryRequest request);

  OrderReceiptResponse vo2Response(OrderReceiptVO vo);

  OrderReceiptDocument entity2Document(OrderReceipt entity);

  OrderReceipt registerModel2Entity(OrderRegisterModel model);

  default OrderReceiptResponse vo2CustomResponse(OrderReceiptVO vo) {
    OrderReceiptResponse response = vo2Response(vo);
    return response;
  }

  OrderReceiptCreator model2Creator(OrderRegisterModel model);
}
