// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.invoice.orderreceipt.ReceiptItem;
import com.only4play.system.domain.invoice.orderreceipt.creator.ReceiptItemCreator;
import com.only4play.system.domain.invoice.orderreceipt.domainservice.model.register.OrderRegisterResultModel.ReceiptItemModel;
import com.only4play.system.domain.invoice.orderreceipt.query.ReceiptItemQuery;
import com.only4play.system.domain.invoice.orderreceipt.request.ReceiptItemCreateRequest;
import com.only4play.system.domain.invoice.orderreceipt.request.ReceiptItemQueryRequest;
import com.only4play.system.domain.invoice.orderreceipt.request.ReceiptItemUpdateRequest;
import com.only4play.system.domain.invoice.orderreceipt.response.ReceiptItemResponse;
import com.only4play.system.domain.invoice.orderreceipt.updater.ReceiptItemUpdater;
import com.only4play.system.domain.invoice.orderreceipt.vo.ReceiptItemVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface ReceiptItemMapper {
  ReceiptItemMapper INSTANCE = Mappers.getMapper(ReceiptItemMapper.class);

  ReceiptItem dtoToEntity(ReceiptItemCreator dto);

  ReceiptItemUpdater request2Updater(ReceiptItemUpdateRequest request);

  ReceiptItemCreator request2Dto(ReceiptItemCreateRequest request);

  ReceiptItemQuery request2Query(ReceiptItemQueryRequest request);

  ReceiptItemResponse vo2Response(ReceiptItemVO vo);

  ReceiptItemCreator model2Creator(ReceiptItemModel item);

  default ReceiptItemResponse vo2CustomResponse(ReceiptItemVO vo) {
    ReceiptItemResponse response = vo2Response(vo);
    return response;
  }
}
