// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.role.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.system.domain.permission.role.Role;
import com.only4play.system.domain.permission.role.creator.RoleCreator;
import com.only4play.system.domain.permission.role.query.RoleQuery;
import com.only4play.system.domain.permission.role.request.RoleCreateRequest;
import com.only4play.system.domain.permission.role.request.RoleQueryRequest;
import com.only4play.system.domain.permission.role.request.RoleUpdateRequest;
import com.only4play.system.domain.permission.role.response.RoleResponse;
import com.only4play.system.domain.permission.role.updater.RoleUpdater;
import com.only4play.system.domain.permission.role.vo.RoleVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface RoleMapper {
  RoleMapper INSTANCE = Mappers.getMapper(RoleMapper.class);

  Role dtoToEntity(RoleCreator dto);

  RoleUpdater request2Updater(RoleUpdateRequest request);

  RoleCreator request2Dto(RoleCreateRequest request);

  RoleQuery request2Query(RoleQueryRequest request);

  RoleResponse vo2Response(RoleVO vo);

  default RoleResponse vo2CustomResponse(RoleVO vo) {
    RoleResponse response = vo2Response(vo);
    return response;
  }
}
