// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.permission.role.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.permission.role.creator.RoleCreator;
import com.only4play.system.domain.permission.role.query.RoleQuery;
import com.only4play.system.domain.permission.role.updater.RoleUpdater;
import com.only4play.system.domain.permission.role.vo.RoleVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IRoleService {
  /**
   * create
   */
  Long createRole(RoleCreator creator);

  /**
   * update
   */
  void updateRole(RoleUpdater updater);

  /**
   * valid
   */
  void validRole(Long id);

  /**
   * invalid
   */
  void invalidRole(Long id);

  /**
   * findById
   */
  RoleVO findById(Long id);

  /**
   * findByPage
   */
  Page<RoleVO> findByPage(PageRequestWrapper<RoleQuery> query);
}
