// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.verifyrule.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.template.verifyrule.VerifyRuleConfig;
import java.lang.Long;

public interface VerifyRuleConfigRepository extends BaseRepository<VerifyRuleConfig, Long> {
}
