// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.template.selectdict.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.template.selectdict.SelectDict;
import java.lang.Long;

public interface SelectDictRepository extends BaseRepository<SelectDict, Long> {
}
