// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.enterpriserouter.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.jpa.support.EntityOperations;
import com.only4play.system.domain.invoice.enterpriserouter.EnterpriseRouter;
import com.only4play.system.domain.invoice.enterpriserouter.creator.EnterpriseRouterCreator;
import com.only4play.system.domain.invoice.enterpriserouter.mapper.EnterpriseRouterMapper;
import com.only4play.system.domain.invoice.enterpriserouter.query.EnterpriseRouterQuery;
import com.only4play.system.domain.invoice.enterpriserouter.repository.EnterpriseRouterRepository;
import com.only4play.system.domain.invoice.enterpriserouter.updater.EnterpriseRouterUpdater;
import com.only4play.system.domain.invoice.enterpriserouter.vo.EnterpriseRouterVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class EnterpriseRouterServiceImpl implements IEnterpriseRouterService {
  private final EnterpriseRouterRepository enterpriseRouterRepository;

  /**
   * createImpl
   */
  @Override
  public Long createEnterpriseRouter(EnterpriseRouterCreator creator) {
    Optional<EnterpriseRouter> enterpriseRouter = EntityOperations.doCreate(enterpriseRouterRepository)
    .create(() -> EnterpriseRouterMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return enterpriseRouter.isPresent() ? enterpriseRouter.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateEnterpriseRouter(EnterpriseRouterUpdater updater) {
    EntityOperations.doUpdate(enterpriseRouterRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateEnterpriseRouter(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validEnterpriseRouter(Long id) {
    EntityOperations.doUpdate(enterpriseRouterRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidEnterpriseRouter(Long id) {
    EntityOperations.doUpdate(enterpriseRouterRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public EnterpriseRouterVO findById(Long id) {
    Optional<EnterpriseRouter> enterpriseRouter =  enterpriseRouterRepository.findById(id);
    return new EnterpriseRouterVO(enterpriseRouter.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<EnterpriseRouterVO> findByPage(PageRequestWrapper<EnterpriseRouterQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<EnterpriseRouter> page = enterpriseRouterRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new EnterpriseRouterVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
