// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.enterpriserouter.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.invoice.enterpriserouter.creator.EnterpriseRouterCreator;
import com.only4play.system.domain.invoice.enterpriserouter.query.EnterpriseRouterQuery;
import com.only4play.system.domain.invoice.enterpriserouter.updater.EnterpriseRouterUpdater;
import com.only4play.system.domain.invoice.enterpriserouter.vo.EnterpriseRouterVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IEnterpriseRouterService {
  /**
   * create
   */
  Long createEnterpriseRouter(EnterpriseRouterCreator creator);

  /**
   * update
   */
  void updateEnterpriseRouter(EnterpriseRouterUpdater updater);

  /**
   * valid
   */
  void validEnterpriseRouter(Long id);

  /**
   * invalid
   */
  void invalidEnterpriseRouter(Long id);

  /**
   * findById
   */
  EnterpriseRouterVO findById(Long id);

  /**
   * findByPage
   */
  Page<EnterpriseRouterVO> findByPage(PageRequestWrapper<EnterpriseRouterQuery> query);
}
