// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.invoice.orderreceipt.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.system.domain.invoice.orderreceipt.creator.ReceiptItemCreator;
import com.only4play.system.domain.invoice.orderreceipt.query.ReceiptItemQuery;
import com.only4play.system.domain.invoice.orderreceipt.updater.ReceiptItemUpdater;
import com.only4play.system.domain.invoice.orderreceipt.vo.ReceiptItemVO;
import java.lang.Long;
import java.util.List;
import org.springframework.data.domain.Page;

public interface IReceiptItemService {
  /**
   * create
   */
  Long createReceiptItem(ReceiptItemCreator creator);

  /**
   * 批量保存
   * @param creatorList
   */
  void batchCreateReceiptItems(List<ReceiptItemCreator> creatorList);

  /**
   * update
   */
  void updateReceiptItem(ReceiptItemUpdater updater);

  /**
   * findById
   */
  ReceiptItemVO findById(Long id);

  /**
   * findByPage
   */
  Page<ReceiptItemVO> findByPage(PageRequestWrapper<ReceiptItemQuery> query);
}
